# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5cd82496ee7de95fe796e220219288db892965f4c8299a02b0bea43284684d70a9cb96d1ce426307fc31f1ea3a5f69d9fec466fa0f80d9d090f2a86d3dfe91

test:
  secret_key_base: 8eb4981c5326f4458407cbf89c9e860b4b869620ea07b0d592918ba503c11f3d6bd49a731cc0141b8cbd09a0363b1f45afaba70943131de1c69e038d7e381c01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
